server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7h0ai1o3t8c73952md0-a.singapore-postgres.render.com/khanhs_tea_db
spring.datasource.username=khanhs_tea_db_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Quan tr?ng: ??i Dialect sang PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.tomcat.max-http-form-post-size=2MB
server.tomcat.threads.max=50

logging.level.root=INFO
logging.level.com.khanh.teashop.khanhs_tea_bot=INFO

telegram.bot.username=khanhs_tea_bot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

gemini.api-key=${GEMINI_API_KEY}
gemini.model=gemini-2.0-flash
gemini.embedding-model=gemini-embedding-001

qdrant.url=${QDRANT_URL}
qdrant.api-key=${QDRANT_API_KEY}
qdrant.collection=tea_menu_knowledge_v2
qdrant.vector-size=3072

payos.base-url=https://api-merchant.payos.vn
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
payos.return-url=https://khanhs-tea-bot.onrender.com/payment/success
payos.cancel-url=https://khanhs-tea-bot.onrender.com/payment/cancel